### PR TITLE
Better Balkans, Carpathians & Alps for South Slavs

### PR DESCRIPTION
**Pull request by TheDovahkiin97**
https://sl.wikipedia.org/wiki/Nem%C4%8Dija

merge it and i will do real and big commits

### CODE REVIEW

**Comment by TheDovahkiin97** [comment]
nevermind for some reason every "š" in my commit is blanked pls ignore it

**Comment by hmlendea** [comment]
Hello. Sorry for the late response, I was quite busy lately. I will try to review and test this asap.

**Comment by TheDovahkiin97** [comment]
I tried using your ISO 8859-1 encoding (Github told me) but im not sure if all the Š/š and Ž/ž work properly...

**Comment by TheDovahkiin97** [comment]
So apparently GitHub encodes automatically every commit in UTF-8 and i have no idea how to stop it.

**Comment by TheDovahkiin97** [comment]
So every Š/š and Ž/ž is displayed as � and the lines I added are somehow wrongly indented. I tryed using Notepad++ and Visual Studio Code and it looks correct there.

**Comment by TheDovahkiin97** [comment]
Okay indentation is fixed but my github still uploads files with UTF-8 encoding.

**Comment by TheDovahkiin97** [comment]
ignore hip-more-cultural-names.mod

**Comment by TheDovahkiin97** [comment]
So i tried using ATOM editor set windows 1252 as default and liked it with github -> commit and still conversion to UTF-8 plus a bunch of whitespace changes i dont understand

**Comment by TheDovahkiin97** [comment]
OMG it was windows 1252 the entire time it just wasnt displayed in github... you can safely merge it case closed.

**Comment by hmlendea** [comment]
Sorry for not responding in a while.
I have very little free time this week.
I will still try to review the changes ASAP but probably I can only merge it in the weekend (I should be free then)

Yes, indeed GitHub fails to display the WINDOWS-1252 encoding correctly.
As a rule of thumb, as long as your editor of choice displays this encoding as the one being set (For N++ and VS Code it displays in the bottom status bar somewhere in the right) then it should be fine. If it also works in-game then it's definetely fine.

For indentation, you can set the editor to use spaces instead of tabs. IIRC it was 4 spaces for each tab.
Anyway, this is not such a big problem since it won't break the game and it can be fixed at any point with the find and replace function.

In the future I'll want to build a small tool that checks the integrity of the data and validates the encoding and integrate it in GitHub. This way we'll know after each commit if we broke anything.
I'll probably do that in december - I've got the whole month off.

**Comment by TheDovahkiin97** [comment]
Thx for the response! Everything works fine ingame and indentation is also solved and im pretty sure you can merge it safely now 👍

**Comment by TheDovahkiin97** [comment]
Why is your mod not overwriting the games swmh_landed_titles.txt? Example: c_iasi has "croatian = "Yassy"" which I edited in your mod as "croatian = "Jaši"". Same with c_vas. Many names are just wrong...

**Comment by hmlendea** [comment]
I noticed the same behaviour when trying to replace "sh" in romanian names with just "s" (actually it should be 'ș', sh is just a workaround for it as ș is not in the game).
Unfortunately, I don't know yet why this happens.

I'm fairly positive that in the past it used to work fine though.
If I have time, I will investigate it further.

**Comment by TheDovahkiin97** [comment]
c_orava is also not working and this is very interesting because no croatian names are set in the swmh_landed_titles.txt file.

**Comment by hmlendea** [comment]
Hello

I just took a look at the PR and it looks fine.
Since there were so many modifications, I wasn't able to test all of them in-game.

Did you test all / most of them?
What I'm worried about are stray characters from outside the WINDOWS-1252 encoding.

**Comment by TheDovahkiin97** [comment]
Hi
I can assure you that there are no characters from outside win 1252 I was very careful with that.

**Comment by hmlendea** [comment]
Everything is in order then.
I can merge this if you're fine with this as well.

**Comment by TheDovahkiin97** [comment]
Yes im ok with that 👍

**Pull request merged**
