### PR TITLE
Titles and fixes

### PR DESCRIPTION
**Pull request by TheDovahkiin97**

### CODE REVIEW

**Comment by TheDovahkiin97** [comment]
I just noticed that everything I did in hungary is not working...
I dont understand why the code looks just fine...

**Comment by TheDovahkiin97** [comment]
Ok seems like i broke your mod... c_orava is ingame now in d_esztergom and i have no idea why. Its definitely the mod because everything is fine when I disable it.

**Comment by hmlendea** [comment]
b_berzence, c_orava, b_arva and b_liptoszentmiklos have missing quotes in their dynamic names.
Bosnian and karantanci names if I remember it correctly.

**Comment by TheDovahkiin97** [comment]
im sorry idk how that happened but i fixed it now. maybe i will try it out this evening. i hope thats all...

**Comment by TheDovahkiin97** [comment]
i tested it and the result is that c_orava does not work anymore... it was one of the few provinces that worked and now it just doesnt...

**Comment by TheDovahkiin97** [comment]
I found it! :D everything works again its safe to merge now 👍

**Comment by TheDovahkiin97** [comment]
croatia
you can add this picture to your steampage if you want 👍 
however hip is still overwriting with some wrong localisations...

**Comment by hmlendea** [comment]
Nice empire you've got there :D 👍 
I'll sure upload it on the workshop page.

Do you need to make any more changes on this PR, or can I merge it?
I'd like merging it soon so that I can merge my PR as well and solve the conflicts on my side (and there's gonna be a lot of them).

As a note; My PR is about automatically testing the mod. It will fail validations if the syntax is wrong (missing = or ", etc) or if the files are not formatted correctly - and we will be able to see it from GitHub. I made it so that we can avoid bugs and hard-to-spot mistakes.

**Comment by TheDovahkiin97** [comment]
Sounds cool! And you can merge it I have nothing big planned. The picture is cheated btw but I indeed managed to build empires like this :D

**Pull request merged**
